### ISSUE TITLE
add Latte-Dock at bottom, remove standard panel

### ISSUE THREAD

**Issue by star-buck** [blackbird-os/blackbird-ideas#1]
have it look like this:
![Screenshot_20190508_132045](https://user-images.githubusercontent.com/840070/57371869-36ccca00-7194-11e9-9373-a10bf6598fb8.png)

I exported this layout to this file:

**Comment by star-buck** [comment]
updated file:
[black-dock-v1.layout.latte.zip](https://github.com/blackbird-os/blackbird-ideas/files/3165682/black-dock-v1.layout.latte.zip)

**Comment by star-buck** [comment]
updated latte dock:
[black-dock-v1.1.layout.latte.zip](https://github.com/blackbird-os/blackbird-ideas/files/3176945/black-dock-v1.1.layout.latte.zip)

**Comment by star-buck** [comment]
i dont see any latte dock installed?

**Comment by NuLogicSystems** [comment]
Oops, sorry about that. I'll put it on the next ISO. I'm still trying to decide on the best way to remove the defaultPanel.

**Comment by star-buck** [comment]
Clone Netrunner LNF theme to Blackbird LNF?

**Comment by NuLogicSystems** [comment]
No, I've only cloned the netrunner black lnf  to blackbird black lnf.
Did you want both?

I don't see how that would help with removing the panel though.
I do know how to remove the panel, but, would we want that as the default for the lnf theme itself, or as a diversion in our default-settings?

**Comment by star-buck** [comment]
Then use LNF for remove panel or rather define no panel and have latte dock
started.

**Comment by NuLogicSystems** [comment]
OK, will do.
